# Docker Compose example for testing Spring Cloud Bus Kafka

services:
  # Configured through environment variables
  config-server-env:
    depends_on:
      - kafka
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    networks:
      - app-tier
    ports:
      - "8888"
    environment:
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      SPRING_PROFILES_ACTIVE: cloud-bus-kafka
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/spring-cloud-samples/config-repo
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092

  # Configured through mounted config volume
  config-server-dir:
    depends_on:
      - kafka
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    networks:
      - app-tier
    ports:
      - "8888"
    volumes:
      - ./config:/config

  # Configured through system properties
  config-server-props:
    depends_on:
      - kafka
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    networks:
      - app-tier
    ports:
      - "8888"
    environment:
      JAVA_OPTS: >
        -Dmanagement.endpoints.web.exposure.include=*
        -Dspring.profiles.active=cloud-bus-kafka
        -Dspring.cloud.config.server.git.uri=https://github.com/spring-cloud-samples/config-repo
        -Dspring.kafka.bootstrap-servers=kafka:9092

  # Configured through command line arguments
  config-server-args:
    depends_on:
      - kafka
    image: "${REGISTRY:-docker.io}/${IMAGE_NAME:-hyness/spring-cloud-config-server}:${TAG:-latest}"
    networks:
      - app-tier
    command:
      - --management.endpoints.web.exposure.include=*
      - --spring.profiles.active=cloud-bus-kafka
      - --spring.cloud.config.server.git.uri=https://github.com/spring-cloud-samples/config-repo
      - --spring.kafka.bootstrap-servers=kafka:9092
    ports:
      - "8888"

  kafka:
    image: bitnamilegacy/kafka:3.6
    networks:
     - app-tier
    ports:
      - "9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER

networks:
  app-tier:
    driver: bridge